# Generated by Django 4.1.4 on 2022-12-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_employee_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
